### PR TITLE
Explains exclamation marks in graphql schema

### PR DESCRIPTION
**Pull request by Akirtovskis**
Hey @Urigo , this tutorial is really awesome, hopefully this extra tip about exclamation marks will be as useful for other as I found it to be for myself. 

Also we met really briefly at the second day of grapqhl conf.  I am one of the colleagues the Leo was with. :)

### CODE REVIEW

**Comment by Urigo** [comment]
Thank you so much @Akirtovskis !
I've applied your changes to master.

Because Tortilla is currently rewriting the git history, as of today there are only 2 ways of applying your changes:
1. We would manually add them and then push the new history
2. You will learn Tortilla.

The issue with the first one is that then you won't get to see your commit in Github's history.
So for now I've added your name [here](https://github.com/urigo/whatsApp-Clone-Server#external-contributors) to give you the credit you deserve.

and maybe in the future you can learn Tortilla (I also hope we will make it easier to use and also maybe figure out a way to change that git history to accommodate multiple contributions for the same commit, I would love to hear ideas!)

Thank you for your contribution and I hope to get more!

I will deploy a new version of the website early next week

**Comment by Akirtovskis** [comment]
Thanks, sounds great. I will keep going through tutorial and if there's anything I can contribute, I will create PR and try using Tortilla workflow. 

I checked the docs on NPM and they look pretty descriptive of what needs to be done, thanks for guidance. 

Some small things though that I found in NPM page was that : github link was going to 404 and youtube tutorial link is also leading to unavailable.

**Comment by Urigo** [comment]
you mean on the Tortilla readme?

**Comment by Akirtovskis** [comment]
Yes, [https://www.npmjs.com/package/tortilla](https://www.npmjs.com/package/tortilla) . Sorry for not being clear enough.

**Pull request closed without merging**
