### PR TITLE
Step 15 Feature: Add link to Paste JSON as Code extension

### PR DESCRIPTION
**Pull request by reymon359**
Add the link to the Paste JSON as Code VScode extension on the Marketplace to improve the user experience make the tutorial easier to follow.

### CODE REVIEW

**Comment by Urigo** [comment]
Thank you!  Fixed and added you as a co-author [here](https://github.com/Urigo/WhatsApp-Clone-Tutorial/commit/65920f719f67176d26fcf7d8db52f3ec88bc176e)

**Comment by Urigo** [comment]
by the way, this episode is focused on technic that we used to use to later move us to create [GraphQL Mesh](https://twitter.com/UriGoldshtein/status/1242118500795236353?s=20).

Would be cool to get some help to update chapter 15 to use GraphQL Mesh instead!

**Comment by reymon359** [comment]
> by the way, this episode is focused on technic that we used to use to later move us to create [GraphQL Mesh](https://twitter.com/UriGoldshtein/status/1242118500795236353?s=20).
> 
> Would be cool to get some help to update chapter 15 to use GraphQL Mesh instead!

Yeah, I read about GraphQL Mesh in one of yours or The Guild social media, and while I was reading it I remembered so much this tutorial step where you have to fetch the data from a REST API too. 

Right now I am still learning GraphQL as I love the idea behind it and how it solves a lot of problems in an easier way than REST and If I can collaborate in anything around it would be awesome. So count with me and I would gladly help you guys in whatever I can!

**Comment by Urigo** [comment]
@reymon359 whenever you are ready, I'm here to start working on that together!

**Comment by reymon359** [comment]
That sounds great @Urigo , I will message you then!

**Pull request closed without merging**
